//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HostelManagmentProject.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback regstOperationCompleted;
        
        private System.Threading.SendOrPostCallback reggkOperationCompleted;
        
        private System.Threading.SendOrPostCallback regrtOperationCompleted;
        
        private System.Threading.SendOrPostCallback regadminOperationCompleted;
        
        private System.Threading.SendOrPostCallback isAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback isStudentOperationCompleted;
        
        private System.Threading.SendOrPostCallback isRTOperationCompleted;
        
        private System.Threading.SendOrPostCallback isGatekeeperOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::HostelManagmentProject.Properties.Settings.Default.HostelManagmentProject_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event regstCompletedEventHandler regstCompleted;
        
        /// <remarks/>
        public event reggkCompletedEventHandler reggkCompleted;
        
        /// <remarks/>
        public event regrtCompletedEventHandler regrtCompleted;
        
        /// <remarks/>
        public event regadminCompletedEventHandler regadminCompleted;
        
        /// <remarks/>
        public event isAdminCompletedEventHandler isAdminCompleted;
        
        /// <remarks/>
        public event isStudentCompletedEventHandler isStudentCompleted;
        
        /// <remarks/>
        public event isRTCompletedEventHandler isRTCompleted;
        
        /// <remarks/>
        public event isGatekeeperCompletedEventHandler isGatekeeperCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/regst", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void regst([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string question, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string answer) {
            this.Invoke("regst", new object[] {
                        username,
                        password,
                        question,
                        answer});
        }
        
        /// <remarks/>
        public void regstAsync(string username, string password, string question, string answer) {
            this.regstAsync(username, password, question, answer, null);
        }
        
        /// <remarks/>
        public void regstAsync(string username, string password, string question, string answer, object userState) {
            if ((this.regstOperationCompleted == null)) {
                this.regstOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregstOperationCompleted);
            }
            this.InvokeAsync("regst", new object[] {
                        username,
                        password,
                        question,
                        answer}, this.regstOperationCompleted, userState);
        }
        
        private void OnregstOperationCompleted(object arg) {
            if ((this.regstCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.regstCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/reggk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void reggk([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string question, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string answer) {
            this.Invoke("reggk", new object[] {
                        username,
                        password,
                        question,
                        answer});
        }
        
        /// <remarks/>
        public void reggkAsync(string username, string password, string question, string answer) {
            this.reggkAsync(username, password, question, answer, null);
        }
        
        /// <remarks/>
        public void reggkAsync(string username, string password, string question, string answer, object userState) {
            if ((this.reggkOperationCompleted == null)) {
                this.reggkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreggkOperationCompleted);
            }
            this.InvokeAsync("reggk", new object[] {
                        username,
                        password,
                        question,
                        answer}, this.reggkOperationCompleted, userState);
        }
        
        private void OnreggkOperationCompleted(object arg) {
            if ((this.reggkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reggkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/regrt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void regrt([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string question, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string answer) {
            this.Invoke("regrt", new object[] {
                        username,
                        password,
                        question,
                        answer});
        }
        
        /// <remarks/>
        public void regrtAsync(string username, string password, string question, string answer) {
            this.regrtAsync(username, password, question, answer, null);
        }
        
        /// <remarks/>
        public void regrtAsync(string username, string password, string question, string answer, object userState) {
            if ((this.regrtOperationCompleted == null)) {
                this.regrtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregrtOperationCompleted);
            }
            this.InvokeAsync("regrt", new object[] {
                        username,
                        password,
                        question,
                        answer}, this.regrtOperationCompleted, userState);
        }
        
        private void OnregrtOperationCompleted(object arg) {
            if ((this.regrtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.regrtCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/regadmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void regadmin([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string question, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string answer) {
            this.Invoke("regadmin", new object[] {
                        username,
                        password,
                        question,
                        answer});
        }
        
        /// <remarks/>
        public void regadminAsync(string username, string password, string question, string answer) {
            this.regadminAsync(username, password, question, answer, null);
        }
        
        /// <remarks/>
        public void regadminAsync(string username, string password, string question, string answer, object userState) {
            if ((this.regadminOperationCompleted == null)) {
                this.regadminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregadminOperationCompleted);
            }
            this.InvokeAsync("regadmin", new object[] {
                        username,
                        password,
                        question,
                        answer}, this.regadminOperationCompleted, userState);
        }
        
        private void OnregadminOperationCompleted(object arg) {
            if ((this.regadminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.regadminCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/isAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void isAdmin([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool isAdminResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool isAdminResultSpecified) {
            object[] results = this.Invoke("isAdmin", new object[] {
                        username,
                        password});
            isAdminResult = ((bool)(results[0]));
            isAdminResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void isAdminAsync(string username, string password) {
            this.isAdminAsync(username, password, null);
        }
        
        /// <remarks/>
        public void isAdminAsync(string username, string password, object userState) {
            if ((this.isAdminOperationCompleted == null)) {
                this.isAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisAdminOperationCompleted);
            }
            this.InvokeAsync("isAdmin", new object[] {
                        username,
                        password}, this.isAdminOperationCompleted, userState);
        }
        
        private void OnisAdminOperationCompleted(object arg) {
            if ((this.isAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isAdminCompleted(this, new isAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/isStudent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void isStudent([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool isStudentResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool isStudentResultSpecified) {
            object[] results = this.Invoke("isStudent", new object[] {
                        username,
                        password});
            isStudentResult = ((bool)(results[0]));
            isStudentResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void isStudentAsync(string username, string password) {
            this.isStudentAsync(username, password, null);
        }
        
        /// <remarks/>
        public void isStudentAsync(string username, string password, object userState) {
            if ((this.isStudentOperationCompleted == null)) {
                this.isStudentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisStudentOperationCompleted);
            }
            this.InvokeAsync("isStudent", new object[] {
                        username,
                        password}, this.isStudentOperationCompleted, userState);
        }
        
        private void OnisStudentOperationCompleted(object arg) {
            if ((this.isStudentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isStudentCompleted(this, new isStudentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/isRT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void isRT([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool isRTResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool isRTResultSpecified) {
            object[] results = this.Invoke("isRT", new object[] {
                        username,
                        password});
            isRTResult = ((bool)(results[0]));
            isRTResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void isRTAsync(string username, string password) {
            this.isRTAsync(username, password, null);
        }
        
        /// <remarks/>
        public void isRTAsync(string username, string password, object userState) {
            if ((this.isRTOperationCompleted == null)) {
                this.isRTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisRTOperationCompleted);
            }
            this.InvokeAsync("isRT", new object[] {
                        username,
                        password}, this.isRTOperationCompleted, userState);
        }
        
        private void OnisRTOperationCompleted(object arg) {
            if ((this.isRTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isRTCompleted(this, new isRTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/isGatekeeper", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void isGatekeeper([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool isGatekeeperResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool isGatekeeperResultSpecified) {
            object[] results = this.Invoke("isGatekeeper", new object[] {
                        username,
                        password});
            isGatekeeperResult = ((bool)(results[0]));
            isGatekeeperResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void isGatekeeperAsync(string username, string password) {
            this.isGatekeeperAsync(username, password, null);
        }
        
        /// <remarks/>
        public void isGatekeeperAsync(string username, string password, object userState) {
            if ((this.isGatekeeperOperationCompleted == null)) {
                this.isGatekeeperOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisGatekeeperOperationCompleted);
            }
            this.InvokeAsync("isGatekeeper", new object[] {
                        username,
                        password}, this.isGatekeeperOperationCompleted, userState);
        }
        
        private void OnisGatekeeperOperationCompleted(object arg) {
            if ((this.isGatekeeperCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isGatekeeperCompleted(this, new isGatekeeperCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void regstCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void reggkCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void regrtCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void regadminCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void isAdminCompletedEventHandler(object sender, isAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool isAdminResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool isAdminResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void isStudentCompletedEventHandler(object sender, isStudentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isStudentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isStudentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool isStudentResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool isStudentResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void isRTCompletedEventHandler(object sender, isRTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isRTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isRTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool isRTResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool isRTResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void isGatekeeperCompletedEventHandler(object sender, isGatekeeperCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isGatekeeperCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isGatekeeperCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool isGatekeeperResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool isGatekeeperResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591